---
title: "Mars missions"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
I used [this r-bloggers post](https://www.r-bloggers.com/2018/09/scraping-tables-from-wikipedia-for-visualizing-climate-data/) and [this David Witkowski post](https://dwitkowski.eu/webscraping_wikipedia/) to learn how to get the data from Wikipedia, and [this is the Wikipedia article I used](https://en.wikipedia.org/wiki/List_of_missions_to_Mars).
```{r}
# Scraping
library("rvest")
# Melting
library("data.table")

library("dplyr")
library("ggplot2")
library("ggthemes")
library(kableExtra)
```

```{r}
url <- "https://en.wikipedia.org/wiki/List_of_missions_to_Mars"
#kept_columns <- c("Record high 째F (째C)","Record low 째F (째C)")
webpage <- read_html(url)

# Use CSS selectors to scrape the table
table <- html_nodes(webpage,'table.wikitable')[[1]]

# Converting the table to a data frame
table <- html_table(table, header = TRUE)

mars <- table %>%
  bind_rows() %>%
  as_tibble()

knitr::kable(head(mars), booktabs = TRUE) %>%
  kable_styling(font_size = 10)

```
